Repository nijesmik/ft_irc, pull requests merged in 2024-08, with the labels that each got.

#5 PING
  include/ChatService.hpp
  include/Message.hpp
  src/ChatService/ping.cpp
  src/EventController.cpp
  src/Parser.cpp
Labels: feature

#7 NICK
  include/NumericReply.hpp
  include/Server.hpp
  include/Session.hpp
  src/ChatService/nick.cpp
  src/NumericReply.cpp
  src/Server.cpp
  src/Session.cpp
Labels: feature

#8 PASS
  include/Session.hpp
  src/ChatService/pass.cpp
  src/Session.cpp
Labels: feature

#11 USER
  include/ChatService.hpp
  include/Message.hpp
  include/Session.hpp
  src/ChatService.cpp
  src/ChatService/nick.cpp
  src/ChatService/user.cpp
  src/EventController.cpp
  src/Message.cpp
  src/Parser.cpp
  src/Session.cpp
Labels: feature

#13 JOIN
  include/Channel.hpp
  include/ChannelService.hpp
  include/EventController.hpp
  include/Message.hpp
  src/Channel.cpp
  src/ChannelService.cpp
  src/EventController.cpp
  src/Parser.cpp
  src/commands/join.cpp
Labels: feature

#15 PART
  include/Channel.hpp
  include/ChannelService.hpp
  include/Message.hpp
  include/NumericReply.hpp
  include/Session.hpp
  src/Channel.cpp
  src/Message.cpp
  src/NumericReply.cpp
  src/Session.cpp
  src/commands/join.cpp
  src/part.cpp
Labels: feature

#20 KICK
  include/Channel.hpp
  include/ChannelService.hpp
  include/NumericReply.hpp
  src/Channel.cpp
  src/NumericReply.cpp
  src/commands/kick.cpp
Labels: feature

#22 TOPIC
  include/Channel.hpp
  include/ChannelService.hpp
  include/Message.hpp
  include/NumericReply.hpp
  src/Channel.cpp
  src/EventController.cpp
  src/Message.cpp
  src/NumericReply.cpp
  src/Parser.cpp
  src/commands/topic.cpp
Labels: feature

#16 JOIN
  include/Channel.hpp
  include/ChannelService.hpp
  include/NumericReply.hpp
  src/Channel.cpp
  src/NumericReply.cpp
  src/commands/join.cpp
Labels: feature

#26 Numeric Reply 메소드 호출 방식 통일
  include/Message.hpp
  include/NumericReply.hpp
  src/ChatService.cpp
  src/Message.cpp
  src/NumericReply.cpp
  src/commands/join.cpp
  src/commands/kick.cpp
  src/commands/nick.cpp
  src/commands/part.cpp
  src/commands/pass.cpp
  src/commands/ping.cpp
  src/commands/topic.cpp
  src/commands/user.cpp
Labels: refactor

#27 MODE
  Makefile
  include/Channel.hpp
  include/ChannelService.hpp
  include/NumericReply.hpp
  include/Parser.hpp
  src/Channel.cpp
  src/Channel/mode.cpp
  src/NumericReply.cpp
  src/Parser.cpp
  src/commands/mode.cpp
Labels: feature

#28 JOIN
  include/Channel.hpp
  include/NumericReply.hpp
  src/Channel/mode.cpp
  src/commands/join.cpp
Labels: feature

#32 INVITE
  include/Channel.hpp
  include/ChannelService.hpp
  include/NumericReply.hpp
  include/Session.hpp
  src/Channel.cpp
  src/ChannelService.cpp
  src/EventController.cpp
  src/NumericReply.cpp
  src/Session.cpp
  src/commands/invite.cpp
Labels: feature

#30 QUIT
  include/Channel.hpp
  include/ChannelService.hpp
  include/ChatService.hpp
  include/Session.hpp
  src/Channel.cpp
  src/EventController.cpp
  src/Session.cpp
  src/commands/quit.cpp
Labels: feature

#35 TOPIC
  include/Channel.hpp
  include/ChannelService.hpp
  src/Channel.cpp
  src/Channel/topic.cpp
  src/EventController.cpp
  src/commands/join.cpp
  src/commands/topic.cpp
Labels: feature

#37 TOPIC
  include/Channel.hpp
  src/Channel/topic.cpp
  src/commands/topic.cpp
Labels: fix

#33 SessionService를 ConnectionService와 SessionRepository로 구조 개선
  Makefile
  include/Channel.hpp
  include/ChannelService.hpp
  include/ChatService.hpp
  include/ConnectionService.hpp
  include/EventController.hpp
  include/NumericReply.hpp
  include/Session.hpp
  include/SessionRepository.hpp
  include/SessionService.hpp
  src/ChatService.cpp
  src/SessionService.cpp
  src/commands/join.cpp
  src/commands/quit.cpp
  src/controller/EventController.cpp
  src/domain/Channel.cpp
  src/domain/Channel/join.cpp
  src/domain/Channel/mode.cpp
  src/domain/Channel/topic.cpp
  src/domain/Message.cpp
  src/domain/NumericReply.cpp
  src/domain/Session.cpp
  src/domain/Socket.cpp
  src/repository/SessionRepository.cpp
  src/service/ChannelService.cpp
  src/service/ChannelService/invite.cpp
  src/service/ChannelService/join.cpp
  src/service/ChannelService/kick.cpp
  src/service/ChannelService/mode.cpp
  src/service/ChannelService/part.cpp
  src/service/ChannelService/quit.cpp
  src/service/ChannelService/topic.cpp
  src/service/ConnectionService.cpp
  src/service/ConnectionService/nick.cpp
  src/service/ConnectionService/pass.cpp
  src/service/ConnectionService/ping.cpp
  src/service/ConnectionService/user.cpp
  src/util/Parser.cpp
Labels: refactor

#39 BOT
  include/BotService.hpp
  include/EventController.hpp
  include/Message.hpp
  src/controller/EventController.cpp
  src/service/BotService.cpp
  src/util/Parser.cpp
Labels: feature

#40 PRIVMSG
  include/Channel.hpp
  include/ChannelService.hpp
  src/domain/Channel.cpp
  src/service/ChannelService/privmsg.cpp
  src/util/Parser.cpp
Labels: feature
